export enum EventsEnum {
    GET_SOCKET_ID = 'get_socket_id',
    ADD_CHAT = 'add_chat',
    CREATE_CHAT = 'create_chat',
    CHANGE_LANGUAGE = 'CHANGE_LANGUAGE',
    CREATE_MESSAGE = 'create_message',
    READ_MESSAGE = 'read_message',
    REMOVE_CHAT = 'remove_chat',
    UPDATE_BADGE = 'update_badge',
    UPDATE_CHAT_ONLINE = 'chat_count_online',
    UPDATE_MAX_USERS_ONLINE = 'max_users_online',
    CLOSE_SOCKET = 'close_socket',
    PLAY_NOTIFICATION = 'play_notification',
    PONG = 'pong',
    ERROR = 'error',
}
