export enum EventsEnum {
    GET_SOCKET_ID = 'get_socket_id',
    CLOSE_SOCKET = 'close_socket',
    SHOW_TEXT = 'show_text',
    CHANGE_LANGUAGE = 'change_language',
    CREATE_MESSAGE = 'create_message',
    UPDATE_ME = 'update_me',
    UPDATE_BADGE = 'update_badge',
    PLAY_NOTIFICATION = 'play_notification',
    PONG = 'pong',
    VERIFY = 'verify',
    ERROR = 'error',
    LOGOUT = 'LOGOUT',
    CREATE_USER = 'create_user',
    UPDATE_CHAT = 'update_chat',
    JOIN_CHAT = 'join_chat',
    LEAVE_CHAT = 'leave_chat',

    SET_STATE_APP = 'set_state_app',
}
