version: "3.4"
services:
  tons-chat-client:
    container_name: tons-chats-client
    image: nginx:latest
    ports:
      - 2223:2223
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
